api_token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5X2lkIjoiZDViZThiNmYtZDgxZi00ZjEyLTgzMWItZTE4ZGNkZTIwZGFiIiwiYXVkIjoiYXMiLCJpc3MiOiJhcyIsIm5iZiI6MTY5Njc5ODE1Nywic3ViIjoiYXBpX2tleSJ9.i31uPCg0IHVCMyg3tRMR-FLzrMVeWRW_Dq-6pziATeI
server: host.docker.internal:8090
network_server:
  name: Network Server
  url: chirpstack-network-server:8000
service_profile:
  name: Service Profile
gateways:
  - id: fcc23dfffe0b9f67
    name: LorixOne-1
  - id: 2CF7F1114110000E
    name: SEEED-SenseCap
application:
  name: app
http_integration:
  url: http://host.docker.internal:8080/chirpstack
device_profiles:
  - name: DDRN Node
    mac_version: 1.1.0
    reg_params_revision: A
    supports_join: True
